# Extra autostart processes
# exec-once = uwsm-app -- my-service

exec-once = nm-applet
exec-once = hyprctl setcursor macOS 48
exec-once = /usr/lib/polkit-kde-authentication-agent-1 || polkit-authentication-agent-1 # polkit agent for authentication
exec-once = sleep 3 && udiskie --appindicator -s -a -n --no-menu-checkbox-workaround # auto-mount with smart tray

# TODO: use uwsm-app for these or maybe remove uwsm dependency???????
exec-once = QT_QPA_PLATFORMTHEME=gtk3 QT_FONT_DPI=80 caelestia shell -d # requires 'extra/papirus-icon-theme' for icons fix with gtk3

# ================= Omarchy default autostart apps =================
# TODO: hmm maybe remove those if not needed

exec-once = /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1

# Slow app launch fix -- set systemd vars
exec-once = systemctl --user import-environment $(env | cut -d'=' -f 1)
exec-once = dbus-update-activation-environment --systemd --all


# exec-once = wl-paste --watch cliphist store
exec-once = walker --gapplication-service
