# Extra autostart processes
# exec-once = uwsm-app -- my-service

exec-once = nm-applet
exec-once = hyprctl setcursor macOS 42
exec-once = /usr/lib/polkit-kde-authentication-agent-1 || polkit-authentication-agent-1 # polkit agent for authentication
exec-once = sleep 3 && udiskie --appindicator -s -a -n --no-menu-checkbox-workaround # auto-mount with smart tray

# TODO: use uwsm-app for these or maybe remove uwsm dependency???????
exec-once = QT_QPA_PLATFORMTHEME=gtk3 QT_FONT_DPI=80 caelestia shell -d # requires 'extra/papirus-icon-theme' for icons fix with gtk3

