# Extra env variables
# env = MY_GLOBAL_ENV,setting
# Cursor size
env = XCURSOR_SIZE,48
env = HYPRCURSOR_SIZE,48

# Allow better support for screen sharing (Google Meet, Discord, etc)
env = XDG_CURRENT_DESKTOP,Hyprland
env = XDG_SESSION_DESKTOP,Hyprland

# Qt
env = QT_QPA_PLATFORMTHEME, qt6ct

# wayland as platform
env = QT_QPA_PLATFORM, wayland

xwayland {
  force_zero_scaling = true
}

# Use XCompose file
env = XCOMPOSEFILE,~/.XCompose

# Don't show update on first launch
ecosystem {
  no_update_news = true
}
