# Gazelle WiFi TUI - floating window like Impala
# Using windowrulev2 and initialClass for xdg-terminal-exec compatibility
windowrulev2 = float, initialClass:(Gazelle)
windowrulev2 = center, initialClass:(Gazelle)
windowrulev2 = size 1000 600, initialClass:(Gazelle)

# Geeqie
windowrulev2 = float, initialClass:(geeqie)
windowrulev2 = center, initialClass:(geeqie)
windowrulev2 = size 1200 700, initialClass:(geeqie)


# ============== Omarchy default window rules ==============

# See https://wiki.hyprland.org/Configuring/Window-Rules/ for more
windowrule = suppressevent maximize, class:.*

# Just dash of opacity by default
windowrule = opacity 0.97 0.9, class:.*

# Fix some dragging issues with XWayland
windowrule = nofocus,class:^$,title:^$,xwayland:1,floating:1,fullscreen:0,pinned:0

