# TODO: test window rules properly, some regex are old and not properly checks for other format or case. to fix them
#


# Geeqie
windowrule = float on, match:initial_class (geeqie)
windowrule = center on, match:initial_class (geeqie)
windowrule = size 1200 700, match:initial_class (geeqie)


# ============== Omarchy default window rules ==============

# See https://wiki.hyprland.org/Configuring/Window-Rules/ for more
windowrule = suppress_event maximize, match:class .* # TODO: maybe remove this

# Just dash of opacity by default
windowrule = opacity 0.94 0.9, match:class .*

# just remove transparency by default, opacity dont affect
windowrule = opaque on, match:class .*

# turn off opaque for kitty
windowrule = opaque off, match:class ^.*(kitty).*$

# no focus stealing for kitty 
windowrule = focus_on_activate off, match:class ^.*(kitty).*$

# Fix some dragging issues with XWayland
# windowrule = no_focus on,match:class .*,match:title .*,xwayland:1,floating:1,fullscreen:0,pinned:0 # TODO: cant find new name for xwayland, new version of hyprland so its renamed i guess. To fix this

# =============== DMS Shell window rules ==================

# Opacity for inactive windows
windowrule = opacity 0.9 0.9, match:float 0, match:focus 0

# GNOME apps
windowrule = rounding 12, match:class ^(org\.gnome\.)
windowrule = border_size 0, match:class ^(org\.gnome\..*)

# Terminal apps - no borders
# windowrule = border_size 0, match:class ^(zen)$ # TODO: looks good without borders but can be confusing

# Floating windows
windowrule = float on, match:class ^.*([Cc]alculator).*$
windowrule = float on, match:class ^(blueman-manager)$
windowrule = float on, match:class ^(org\.gnome\.Nautilus)$

# Open DMS windows as floating by default
windowrule = float on, match:class ^(org.quickshell)$


# javafx fix
#
windowrule = float on, match:title ^.*FX$
windowrule = float on, match:title ^(Java)?FX.*$
windowrule = float on, match:class ^.*[a-z0-9]App$
windowrule = float on, match:class ^.*FX$

