# --- General settings ---
set -g base-index 1
set -g mouse on
set -g focus-events on

# Allow passthrough (for image.nvim, etc.)
setw -g allow-passthrough on

# Reload config
bind r source-file ~/.config/tmux/tmux.conf \; display "Reloaded ~/.config/tmux/tmux.conf"

# Split panes easily
bind | split-window -h -c "#{pane_current_path}"
bind - split-window -v -c "#{pane_current_path}"
bind c new-window -c "#{pane_current_path}"

# --- Catppuccin Theme ---
# Recommended defaults: https://github.com/catppuccin/tmux#recommended-default-configuration
set -g @catppuccin_flavor "mocha"
set -g @catppuccin_window_status_style "rounded"

# --- Status Bar ---
set -g status-right-length 100
set -g status-left-length 100

# Left status
set -g status-left ""
set -ag status-left "#{E:@catppuccin_status_session}"

# Right status
set -g status-right "#{E:@catppuccin_status_application}"
set -agF status-right "#{E:@catppuccin_status_cpu}"
set -ag status-right "#{E:@catppuccin_status_uptime}"
set -agF status-right "#{E:@catppuccin_status_battery}"

# --- Plugins ---
# Use TPM (Tmux Plugin Manager)
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'catppuccin/tmux'
set -g @plugin 'tmux-plugins/tmux-cpu'
set -g @plugin 'tmux-plugins/tmux-battery'

# Initialize TMUX plugin manager (keep this line at the very bottom)
run '~/.tmux/plugins/tpm/tpm'

